[package]
name = "rendro"
version = "0.2.3"
edition = "2021"
authors = ["Michael Paul michael.paul38.ctr@mail.mil"]

[dependencies]
base64 = "0.21.0"
minijinja = { version = "2.3.1", features = [ "loader" ] }
structopt = "0.3.26"

[profile.release]
opt-level = 3
